"""
This module defines constants used in the DoIP and UDS protocols.
"""

# DoIP Constants
PROTOCOL_VERSION = 0x03
INVERSE_VERSION = 0xFC

# DoIP Payload Types
PAYLOAD_TYPE_ROUTING_ACTIVATION_REQUEST = 0x0005
PAYLOAD_TYPE_ROUTING_ACTIVATION_RESPONSE = 0x0006
PAYLOAD_TYPE_DIAGNOSTIC_MESSAGE = 0x8001

# UDS Service IDs (SID)
UDS_SID_DIAGNOSTIC_SESSION_CONTROL = 0x10
UDS_SID_ECU_RESET = 0x11
UDS_SID_CLEAR_DIAGNOSTIC_INFORMATION = 0x14
UDS_SID_READ_DTC_INFORMATION = 0x19
UDS_SID_READ_DATA_BY_IDENTIFIER = 0x22
UDS_SID_SECURITY_ACCESS = 0x27
UDS_SID_WRITE_DATA_BY_IDENTIFIER = 0x2E
UDS_SID_ROUTINE_CONTROL = 0x31
UDS_SID_TESTER_PRESENT = 0x3E

# UDS Negative Response Codes (NRC)
UDS_NRC_INCORRECT_MESSAGE_LENGTH_OR_INVALID_FORMAT = 0x13
UDS_NRC_CONDITIONS_NOT_CORRECT = 0x22
UDS_NRC_REQUEST_OUT_OF_RANGE = 0x31

# UDS Routine Control Sub-functions
UDS_ROUTINE_CONTROL_START_ROUTINE = 0x01
UDS_ROUTINE_CONTROL_STOP_ROUTINE = 0x02
UDS_ROUTINE_CONTROL_REQUEST_ROUTINE_RESULTS = 0x03

# UDS ECU Reset Sub-functions
UDS_ECU_RESET_HARD_RESET = 0x01
UDS_ECU_RESET_SOFT_RESET = 0x03

# UDS Data Identifiers (DID)
UDS_DID_VIN = 0xF190
UDS_DID_ECU_SOFTWARE_VERSION = 0xF195
